//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceGames
    {
        public int DeviceGameID { get; set; }
        public int DeviceID { get; set; }
        public int GameID { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Games Games { get; set; }
    }
}
