//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sessions()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int SessionID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public int ClientID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Status { get; set; }
        public bool IsFrozen { get; set; }
        public Nullable<System.DateTime> FreezeStartTime { get; set; }
        public Nullable<int> MaxFreezeMinutes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Devices Devices { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Reservations Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
