//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int TransactionID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public decimal Amount { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Reservations Reservations { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
